name: cv2
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10.14
  - pip=23.3.1
  - pytorch-cuda=12.1
  - pytorch=2.2.1
  - torchvision=0.17.1
  - torchaudio=2.2.1
  - pip:
    - wheel
    - tqdm
    - lightning
    - black
    - ruff
    - hydra-core
    - jaxtyping
    - beartype
    - wandb
    - einops
    - colorama
    - scikit-image
    - colorspacious
    - matplotlib
    - moviepy
    - imageio
    - git+https://github.com/dcharatan/diff-gaussian-rasterization-modified
    - timm
    - dacite
    - lpips
    - e3nn
    - plyfile
    - tabulate
    - svg.py