# @package _global_

dataset:
  view_sampler:
    min_distance_between_context_views: 135
    max_distance_between_context_views: 135
    min_distance_to_context_views: 12 # must be smaller than initial_min_distance_between_context_views / 2
    warm_up_steps: 150_000
    initial_min_distance_between_context_views: 25
    initial_max_distance_between_context_views: 25
    num_target_views: 4
